### ISSUE TITLE
Ability to set MediaQuery textScaleFactor

### ISSUE THREAD

**Issue by lohnn** [bluefireteam/dashbook#94]
Testing gallery components for different screen sizes is easy with the device picker, but further emulating a user's device with setting a text scale factor would be a neat improvement.

I would love to take a stab at it.

**Comment by erickzanardo** [comment]
That is a very good idea. I think it would be nice if we could somehow tie this property with the device picker somehow since I feel that they are related, maybe this could be a new property on the custom device frame modal?

Looking forward to any PRs and feel free to hit me if you need help. Thanks

**Comment by lohnn** [comment]
Already on it ;)
![image](https://user-images.githubusercontent.com/960157/199075206-ff861d23-eefd-4103-aa37-9f63246fc544.png)

**Comment by lohnn** [comment]
We could probably close this as well. I'm the long term it would be nice to allow for bigger variety of options. But IMHO this particular issue could be considered done, paving the way for more options in the future ☺️

**Comment by erickzanardo** [comment]
Agreed! Closing this, thanks a lot for the time you putted in this
